---
abstract: 'Create MaxMind DB database files'
author:
  - 'Olaf Alders <oalders@maxmind.com>'
  - 'Greg Oschwald <goschwald@maxmind.com>'
  - 'Dave Rolsky <drolsky@maxmind.com>'
build_requires:
  Data::Printer: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  List::AllUtils: '0'
  List::Util: '0'
  Module::Build: '0.28'
  Net::Works::Address: '0'
  Scalar::Util: '0'
  Test::Bits: '0'
  Test::Fatal: '0'
  Test::MaxMind::DB::Common::Data: '0'
  Test::More: '0.88'
  Test::Requires: '0'
  autodie: '0'
  lib: '0'
  perl: '5.010'
  utf8: '0'
configure_requires:
  Capture::Tiny: '0'
  Carp: '0'
  Config::AutoConf: '0'
  Exporter: '0'
  ExtUtils::CBuilder: '0'
  File::Basename: '0'
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  Module::Build: '0.28'
  PerlIO: '0'
  Scalar::Util: '0'
  base: '0'
  lib: '0'
  perl: '5.008002'
  strict: '0'
  warnings: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MaxMind-DB-Writer
provides:
  MaxMind::DB::Writer:
    file: lib/MaxMind/DB/Writer.pm
    version: '0.060000'
  MaxMind::DB::Writer::Serializer:
    file: lib/MaxMind/DB/Writer/Serializer.pm
    version: '0.060000'
  MaxMind::DB::Writer::Tree:
    file: lib/MaxMind/DB/Writer/Tree.pm
    version: '0.060000'
  MaxMind::DB::Writer::Tree::Processor::VisualizeTree:
    file: lib/MaxMind/DB/Writer/Tree/Processor/VisualizeTree.pm
    version: '0.060000'
  MaxMind::DB::Writer::Util:
    file: lib/MaxMind/DB/Writer/Util.pm
    version: '0.060000'
requires:
  Carp: '0'
  Data::Dumper::Concise: '0'
  Data::IEEE754: '0'
  Devel::Dwarn: '0'
  Digest::MD5: '0'
  Digest::SHA1: '0'
  Encode: '0'
  Exporter: '0'
  IO::Handle: '0'
  Math::Int128: '0.06'
  MaxMind::DB::Common: '0.031003'
  MaxMind::DB::Metadata: '0'
  MaxMind::DB::Reader::Decoder: '0'
  MaxMind::DB::Role::Debugs: '0'
  Moose: '0'
  Moose::Util::TypeConstraints: '0'
  MooseX::StrictConstructor: '0'
  Net::Works: '0.20'
  Net::Works::Network: '0'
  Sereal::Encoder: '0'
  Test::Deep::NoTest: '0'
  XSLoader: '0'
  bytes: '0'
  constant: '0'
  namespace::autoclean: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/maxmind/MaxMind-DB-Writer-perl/issues
  repository: git://github.com/maxmind/MaxMind-DB-Writer-perl.git
version: '0.060000'
x_Dist_Zilla:
  perl:
    version: '5.016003'
  plugins:
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@MAXMIND/Authority'
      version: '1.009'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@MAXMIND/AutoPrereqs'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@MAXMIND/CopyFilesFromBuild'
      version: '0.103510'
    -
      class: Dist::Zilla::Plugin::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename:
            - README.md
            - cpanfile
            - Makefile.PL
            - LICENSE
          exclude_match: []
          follow_symlinks: '0'
          include_dotfiles: '0'
          prefix: ''
          prune_directory: []
          root: .
      name: '@MAXMIND/GatherDir'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@MAXMIND/GitHub::Meta'
      version: '0.38'
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@MAXMIND/GitHub::Update'
      version: '0.38'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@MAXMIND/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '5.025'
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: '@MAXMIND/MetaProvides::Package'
      version: '2.001002'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@MAXMIND/NextRelease'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      name: '@MAXMIND/Test::PodSpelling'
      version: '2.006008'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@MAXMIND/Test::ReportPrereqs'
      version: '0.019'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@MAXMIND/TestMoreDoneTesting'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: '1'
          check_all_prereqs: '1'
          modules: []
          phase: release
          skip:
            - Dist::Zilla::Plugin::MAXMIND::Contributors
            - Dist::Zilla::Plugin::MAXMIND::License
      name: '@MAXMIND/stale modules, release'
      version: '0.029'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@MAXMIND/ReadmeMarkdownInBuild'
      version: '0.142470'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@MAXMIND/ReadmeMarkdownInRoot'
      version: '0.142470'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@MAXMIND/UploadToCPAN'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@MAXMIND/PruneCruft'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@MAXMIND/ManifestSkip'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@MAXMIND/MetaYAML'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::License
      name: '@MAXMIND/License'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@MAXMIND/ExtraTests'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@MAXMIND/ExecDir'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@MAXMIND/ShareDir'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@MAXMIND/Manifest'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@MAXMIND/TestRelease'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@MAXMIND/ConfirmRelease'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@MAXMIND/CheckPrereqsIndexed'
      version: '0.012'
    -
      class: Dist::Zilla::Plugin::CPANFile
      name: '@MAXMIND/CPANFile'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      config:
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@MAXMIND/Git::CheckFor::CorrectBranch'
      version: '0.011'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::MergeConflicts
      config:
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@MAXMIND/Git::CheckFor::MergeConflicts'
      version: '0.011'
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: '@MAXMIND/Git::Describe'
      version: '0.003'
    -
      class: Dist::Zilla::Plugin::Git::Contributors
      config:
        Dist::Zilla::Plugin::Git::Contributors:
          include_authors: '0'
          include_releaser: '1'
          order_by: name
          paths: []
      name: '@MAXMIND/Git::Contributors'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@MAXMIND/InstallGuide'
      version: '1.200005'
    -
      class: Dist::Zilla::Plugin::MAXMIND::Contributors
      name: '@MAXMIND/MAXMIND::Contributors'
      version: '0.03'
    -
      class: Dist::Zilla::Plugin::MAXMIND::License
      name: '@MAXMIND/MAXMIND::License'
      version: '0.03'
    -
      class: Dist::Zilla::Plugin::Meta::Contributors
      name: '@MAXMIND/Meta::Contributors'
      version: '0.001'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@MAXMIND/MetaConfig'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@MAXMIND/MetaJSON'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@MAXMIND/MinimumPerl'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@MAXMIND/PkgVersion'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::SurgicalPodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Name
              name: Name
              version: '4.006'
            -
              class: Pod::Weaver::Section::Version
              name: Version
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: prelude
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.006'
            -
              class: Pod::Weaver::Section::Leftovers
              name: Leftovers
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: postlude
              version: '4.006'
            -
              class: Pod::Weaver::Section::Authors
              name: Authors
              version: '4.006'
            -
              class: Pod::Weaver::Section::Contributors
              name: Contributors
              version: '0.008'
            -
              class: Pod::Weaver::Section::Legal
              name: Legal
              version: '4.006'
      name: '@MAXMIND/SurgicalPodWeaver'
      version: '0.0023'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@MAXMIND/PodSyntaxTests'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@MAXMIND/Test::CPAN::Changes'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: '0'
          fail_on_warning: author
          fake_home: '0'
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: '0'
          phase: test
          script_finder:
            - ':ExecFiles'
          skips: []
      name: '@MAXMIND/Test::Compile'
      version: '2.051'
    -
      class: Dist::Zilla::Plugin::Test::EOL
      config:
        Dist::Zilla::Plugin::Test::EOL:
          filename: xt/author/eol.t
      name: '@MAXMIND/Test::EOL'
      version: '0.15'
    -
      class: Dist::Zilla::Plugin::Test::NoTabs
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          filename: xt/author/no-tabs.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
      name: '@MAXMIND/Test::NoTabs'
      version: '0.09'
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@MAXMIND/Test::Portability'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Test::Synopsis
      name: '@MAXMIND/Test::Synopsis'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - cpanfile
            - CONTRIBUTING.md
            - LICENSE
            - Makefile.PL
            - README.md
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@MAXMIND/Git::Check'
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - cpanfile
            - CONTRIBUTING.md
            - LICENSE
            - Makefile.PL
            - README.md
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@MAXMIND/Git::Commit'
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: 0
          tag: v0.060000
          tag_format: v%v
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@MAXMIND/Git::Tag'
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@MAXMIND/Git::Push'
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::ModuleBuild::Custom
      name: ModuleBuild::Custom
      version: '4.25'
    -
      class: Dist::Zilla::Plugin::FileFinder::ByName
      name: ':BuildPL'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.025'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@MAXMIND/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '5.025'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.025'
x_authority: cpan:MAXMIND
x_contributors:
  - 'tjmather <tjmather@maxmind.com>'
